# Purpose: upload newly-published works from Thoth to Project MUSE FTP server.
# Uploads all active Thoth works with a publication date within the previous week.
# Work must have a valid URL supplied as the PDF or EPUB Publication Canonical Location
# and a valid link to a .jpg file supplied as the Cover URL.
# Project MUSE credentials for each relevant publisher must be present as repository secrets
# named MUSE_FTP_USER_[publisher_id] and MUSE_FTP_PW_[publisher_id].
name: muse-bulk-disseminate

on:
  schedule:
    # 'at 02:20 every Thursday'
    # (scheduling is not guaranteed; runs at the start of the hour
    # are more likely to be delayed)
    - cron: '20 2 * * 4'
  workflow_dispatch:

jobs:
  muse-bulk-disseminate:
    uses: ./.github/workflows/bulk_disseminate.yml
    with:
      platform: 'MUSE'
      env_publishers: ${{ vars.MUSE_ENV_PUBLISHERS }}
      env_exceptions: ${{ vars.MUSE_ENV_EXCEPTIONS }}
    secrets: inherit